name: gans-notebooks
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
  - torchtext=0.6.0
  - pillow<7.0 # version 7 breaks torchvision 0.4.2 and earlier
  - ipython>=7.9
  - numpy
  - scikit-learn
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - ffmpeg>4.1
  - freetype>=2.10
  - scipy
  - pip
  - pip:
    - nbmerge
    - pytest-xdist
    - nltk
    - descartes
    - shapely

